import type { Metadata } from "next";
import { Montserrat, Fraunces, Open_Sans } from "next/font/google";
import "./globals.css";

// Importando as fontes
const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "700"] });
const fraunces = Fraunces({ subsets: ["latin"], weight: ["400", "700"] });
const openSans = Open_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>{children}</body>
    </html>
  );
}
